Applied unit testing to presenters classes
Faka-GLB/Parking-system pull request #9
Opened 2021-07-12 19:37 UTC by Faka-GLB

Created a class for each presenter to apply unit testing on every public method on the presenter class, also tested models within the presenter test class.

![image](https://user-images.githubusercontent.com/84337198/125345497-ff877400-e32e-11eb-8c56-cf841fda37f7.png)

![image](https://user-images.githubusercontent.com/84337198/125345330-cbac4e80-e32e-11eb-983a-1dcbdc18632d.png)

2021-07-12 19:52 UTC, SartiMau requested changes

2021-07-12 19:52 UTC, SartiMau commented on app/src/test/java/com/onboarding/parkingsystemjava/mvp/presenter/ConfigureParkingPresenterTest.java
> +        Mockito.when(view.getLots()).thenReturn(ConstUtils.PARKING_LOT_STRING);
you should not use the constants from the ConstUtils here, please use const local variables

2021-07-12 19:52 UTC, SartiMau commented on app/src/test/java/com/onboarding/parkingsystemjava/mvp/presenter/ReservePresenterTest.java
> +        model.setStartDate(getStartDateCalendar());
you should call the model from the presenter, not call the model directly

2021-07-13 13:24 UTC, SartiMau commented on app/src/test/java/com/onboarding/parkingsystemjava/utils/ConstUtils.java
> +public class ConstUtils {
You should not use this class. each test class should have all the necessary info

2021-07-13 13:55 UTC, SartiMau approved these changes

2021-07-13 14:12 UTC, BQuinteros approved these changes

2021-07-13 17:03 UTC, merged